name: 'Node.js CI'

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  ci_languageserver:
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        working-directory: 'vscode-styled-jsx-languageserver'
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: 'actions/checkout@v2'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: 'actions/setup-node@v2.1.5'
        with:
          node-version: ${{ matrix.node-version }}

      - run: 'npm install'
      - run: 'npm run package'
      - run: 'npm run lint'
      - run: 'xvfb-run -a npm test'
