# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 'Node.js CI'

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci_languageserver_package:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vscode-styled-jsx-languageserver
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run compile
      - run: npm run package

  ci_languageserver_lint_client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vscode-styled-jsx-languageserver/server
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run lint

  ci_languageserver_lint_server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vscode-styled-jsx-languageserver/server
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run lint
