# For more information see: https://github.com/marketplace/actions/github-action-for-vsce

name: 'Deploy Extension'

on:
  push:
    branches: [master]

jobs:
  deploy_languageserver:
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        working-directory: 'vscode-styled-jsx-languageserver'
    steps:
      - uses: 'actions/checkout@v2'

      - uses: 'actions/setup-node@v2.1.4'
        with:
          node-version: 14

      - run: 'npm ci'

      - name: 'Publish to Open VSX Registry'
        uses: 'HaaLeo/publish-vscode-extension@v0'
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          packagePath: './vscode-styled-jsx-languageserver'

      - name: 'Publish to Visual Studio Marketplace'
        uses: 'HaaLeo/publish-vscode-extension@v0'
        with:
          pat: ${{ secrets.VSCE_TOKEN }}
          registryUrl: 'https://marketplace.visualstudio.com'
          packagePath: './vscode-styled-jsx-languageserver'

  deploy_syntax:
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        working-directory: 'vscode-styled-jsx-syntax'
    steps:
      - uses: 'actions/checkout@v2'

      - uses: 'actions/setup-node@v2.1.4'
        with:
          node-version: 14

      - run: 'npm ci'

      - name: 'Publish to Open VSX Registry'
        uses: 'HaaLeo/publish-vscode-extension@v0'
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          packagePath: './vscode-styled-jsx-syntax'

      - name: 'Publish to Visual Studio Marketplace'
        uses: 'HaaLeo/publish-vscode-extension@v0'
        with:
          pat: ${{ secrets.VSCE_TOKEN }}
          registryUrl: 'https://marketplace.visualstudio.com'
          packagePath: './vscode-styled-jsx-syntax'
