# For more information see: https://github.com/marketplace/actions/github-action-for-vsce

name: 'Deploy Extension'

on:
  push:
    branches: [master]

jobs:
  deploy_languageserver:
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        working-directory: 'vscode-styled-jsx-languageserver'
    steps:
      - uses: 'actions/checkout@v2'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: 'actions/setup-node@v2.1.4'
        with:
          node-version: ${{ matrix.node-version }}

      - run: 'npm install'
      - run: 'npm run publish -- --pat $VSCE_TOKEN'
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}

  deploy_syntax:
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        working-directory: 'vscode-styled-jsx-syntax'
    steps:
      - uses: 'actions/checkout@v2'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: 'actions/setup-node@v2.1.4'
        with:
          node-version: ${{ matrix.node-version }}

      - run: 'npm install'
      - run: 'npm run publish -- --pat $VSCE_TOKEN'
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
